# GoReleaser configuration for secretctl
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # CLI binary
  - id: secretctl
    main: ./cmd/secretctl
    binary: secretctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: secretctl
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

# ===========================================
# Homebrew Tap (macOS/Linux)
# ===========================================
brews:
  - name: secretctl
    ids:
      - secretctl
    repository:
      owner: forest6511
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/forest6511/secretctl"
    description: "The simplest AI-ready secrets manager"
    license: "MIT"
    install: |
      bin.install "secretctl"
    test: |
      system "#{bin}/secretctl", "version"

# ===========================================
# Scoop Bucket (Windows)
# ===========================================
scoops:
  - name: secretctl
    ids:
      - secretctl
    repository:
      owner: forest6511
      name: scoop-bucket
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/forest6511/secretctl"
    description: "The simplest AI-ready secrets manager"
    license: MIT

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other'
      order: 999

release:
  github:
    owner: forest6511
    name: secretctl
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## secretctl {{ .Tag }}

    The simplest AI-ready secrets manager.

    ### Installation

    #### macOS / Linux (Homebrew) - Recommended
    ```bash
    brew install forest6511/tap/secretctl
    ```

    #### Windows (Scoop)
    ```powershell
    scoop bucket add secretctl https://github.com/forest6511/scoop-bucket
    scoop install secretctl
    ```

    #### Manual Installation

    **macOS (Apple Silicon)**
    ```bash
    curl -LO https://github.com/forest6511/secretctl/releases/download/{{ .Tag }}/secretctl_{{ .Version }}_darwin_arm64.tar.gz
    tar xzf secretctl_{{ .Version }}_darwin_arm64.tar.gz
    sudo mv secretctl /usr/local/bin/
    ```

    **macOS (Intel)**
    ```bash
    curl -LO https://github.com/forest6511/secretctl/releases/download/{{ .Tag }}/secretctl_{{ .Version }}_darwin_amd64.tar.gz
    tar xzf secretctl_{{ .Version }}_darwin_amd64.tar.gz
    sudo mv secretctl /usr/local/bin/
    ```

    **Linux (x86_64)**
    ```bash
    curl -LO https://github.com/forest6511/secretctl/releases/download/{{ .Tag }}/secretctl_{{ .Version }}_linux_amd64.tar.gz
    tar xzf secretctl_{{ .Version }}_linux_amd64.tar.gz
    sudo mv secretctl /usr/local/bin/
    ```

    **Windows**
    ```powershell
    # Download and extract
    Invoke-WebRequest -Uri "https://github.com/forest6511/secretctl/releases/download/{{ .Tag }}/secretctl_{{ .Version }}_windows_amd64.zip" -OutFile secretctl.zip
    Expand-Archive secretctl.zip -DestinationPath .
    # Move to PATH or run directly
    ```

    ### Verify Installation

    ```bash
    secretctl version
    ```

    ### Verify Download (checksums)

    ```bash
    curl -LO https://github.com/forest6511/secretctl/releases/download/{{ .Tag }}/checksums.txt
    sha256sum -c checksums.txt --ignore-missing
    ```
  footer: |
    ---

    **Full Changelog**: https://github.com/forest6511/secretctl/blob/main/CHANGELOG.md

    **Documentation**: https://forest6511.github.io/secretctl/

# Announce release (optional, disabled by default)
# announce:
#   discord:
#     enabled: false
