name: Bug Report
description: Report a bug or unexpected behavior.
labels: [bug]

body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting.
      options:
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version of secretctl
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Run `secretctl init`
        2. Run `secretctl set KEY`
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: e.g., macOS 14.0, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`

  - type: input
    id: secretctl-version
    attributes:
      label: secretctl Version
      description: Output of `secretctl --version` or commit hash

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant error messages or logs (do NOT include secrets).
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help diagnose the issue.
