name: Feature Request
description: Suggest a new feature or enhancement.
labels: [enhancement]

body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting.
      options:
        - label: I have searched for existing feature requests
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Provide an example of how this feature would be used.
      placeholder: |
        ```bash
        secretctl new-command --flag value
        ```

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references.
