// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<main.PasswordChangeResult>;

export function CheckVaultExists():Promise<boolean>;

export function ClearClipboard():Promise<void>;

export function CopyFieldValue(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateSecret(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function CreateSecretMultiField(arg1:main.SecretUpdateDTO):Promise<void>;

export function DeleteSecret(arg1:string):Promise<void>;

export function GetAuditLogStats():Promise<Record<string, number>>;

export function GetAuthStatus():Promise<main.AuthStatus>;

export function GetSecret(arg1:string):Promise<main.Secret>;

export function GetTemplates():Promise<Array<main.TemplateInfo>>;

export function InitVault(arg1:string):Promise<void>;

export function ListAuditLogs(arg1:number):Promise<Array<main.AuditLogEntry>>;

export function ListSecrets():Promise<Array<main.SecretListItem>>;

export function Lock():Promise<void>;

export function ResetIdleTimer():Promise<void>;

export function SearchAuditLogs(arg1:main.AuditLogFilter,arg2:number,arg3:number):Promise<main.AuditLogSearchResult>;

export function Unlock(arg1:string):Promise<void>;

export function UpdateSecret(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function UpdateSecretMultiField(arg1:main.SecretUpdateDTO):Promise<void>;

export function VerifyAuditLogs():Promise<boolean>;

export function ViewSensitiveField(arg1:string,arg2:string):Promise<void>;
