// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckVaultExists() {
  return window['go']['main']['App']['CheckVaultExists']();
}

export function ClearClipboard() {
  return window['go']['main']['App']['ClearClipboard']();
}

export function CopyFieldValue(arg1, arg2) {
  return window['go']['main']['App']['CopyFieldValue'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateSecret(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSecret'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function GetAuditLogStats() {
  return window['go']['main']['App']['GetAuditLogStats']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetSecret(arg1) {
  return window['go']['main']['App']['GetSecret'](arg1);
}

export function InitVault(arg1) {
  return window['go']['main']['App']['InitVault'](arg1);
}

export function ListAuditLogs(arg1) {
  return window['go']['main']['App']['ListAuditLogs'](arg1);
}

export function ListSecrets() {
  return window['go']['main']['App']['ListSecrets']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function ResetIdleTimer() {
  return window['go']['main']['App']['ResetIdleTimer']();
}

export function SearchAuditLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchAuditLogs'](arg1, arg2, arg3);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateSecret(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateSecret'](arg1, arg2, arg3, arg4, arg5);
}

export function VerifyAuditLogs() {
  return window['go']['main']['App']['VerifyAuditLogs']();
}

export function ViewSensitiveField(arg1, arg2) {
  return window['go']['main']['App']['ViewSensitiveField'](arg1, arg2);
}
